name: build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      
      - name: Build Summary
        run: zig build -DTests --summary all -freference-trace
      
      - name: Test memory map
        run: zig build test_mmap -DTests

      - name: Test process_vm_readv
        run: zig build test_process_vm_readv -DTests -- 26831 0x00007efbf7fd7000 10
